server:
  port: 8001
spring:
  application:
    name: service-prod
#  neo4j:
#    uri: bolt://192.168.236.135:7687
#    authentication:
#      username: neo4j
#      password: 123456
dubbo:
  # 配置服务信息
  application:
    name: service-prod
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://localhost:8848
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 20880

